// @ts-check
import { writeFile, mkdir, readFile } from 'node:fs/promises';
import { join, isAbsolute, resolve, dirname } from 'node:path';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import analyzeStory from '../user-story-analysis/run.mjs';

const __dirname  = dirname(fileURLToPath(import.meta.url));
const FRAMEWORK_ROOT = resolve(__dirname, '..', '..');

/**
 * Phase 3 — E2E Test Generation (JavaScript Playwright, POM pattern)
 * Outputs to: /e2e/pages/<suite>.page.js
 *             /e2e/tests/<suite>.spec.js
 *             /e2e/helpers/  (shared utilities)
 */
export default async function run(ctx) {
  const suite = ctx.args?.suite;
  if (!suite) throw new Error('Missing --suite <name>');
  const safe = suite.replace(/[^a-z0-9-_]/gi, '-').toLowerCase();

  let ast = null;
  if (ctx.args?.story) ast = (await analyzeStory(ctx)).ast;

  const e2eRoot  = ctx.paths?.e2e  ?? join(FRAMEWORK_ROOT, 'e2e');
  const pagesDir = join(e2eRoot, 'pages');
  const testsDir = join(e2eRoot, 'tests');
  const helpDir  = join(e2eRoot, 'helpers');

  await mkdir(pagesDir, { recursive: true });
  await mkdir(testsDir, { recursive: true });
  await mkdir(helpDir,  { recursive: true });

  const pomFile  = join(pagesDir, `${safe}.page.js`);
  const specFile = join(testsDir, `${safe}.spec.js`);
  const authFile = join(helpDir, 'auth.js');
  const utilFile = join(helpDir, 'utils.js');
  const instrFile = join(helpDir, 'instrumentation.js');

  // Write POM (never overwrite — let developer extend)
  if (!existsSync(pomFile))   await writeFile(pomFile,  pomTemplate(safe, ast), 'utf8');
  // Write spec (regenerate each time to stay in sync with story)
  await writeFile(specFile, specTemplate(safe, ast, ctx.config), 'utf8');

  // Write shared helpers only if they don't exist yet
  if (!existsSync(authFile))  await writeFile(authFile,  authHelper(ctx.config), 'utf8');
  if (!existsSync(utilFile))  await writeFile(utilFile,  utilsHelper(), 'utf8');
  if (!existsSync(instrFile)) await writeFile(instrFile, instrumentationHelper(), 'utf8');

  console.log(`✅ E2E tests generated (JavaScript):`);
  console.log(`   POM  : ${pomFile}`);
  console.log(`   Spec : ${specFile}`);

  return { pomFile, specFile, authFile, utilFile };
}

// ─── Page Object Model template ───────────────────────────────────────────────

function pomTemplate(name, ast) {
  const cls = pascal(name) + 'Page';
  const acList = ast?.acceptanceCriteria?.length
    ? ast.acceptanceCriteria.map((ac, i) => ` * ${i + 1}. ${ac}`).join('\n')
    : ' * (no acceptance criteria detected)';

  return `// @ts-check
/**
 * Page Object: ${cls}
 * Auto-generated by AI QA Framework v2 — extend with real selectors.
 *
 * Acceptance Criteria covered:
${acList}
 */
import { expect } from '@playwright/test';

class ${cls} {
  /**
   * @param {import('@playwright/test').Page} page
   */
  constructor(page) {
    this.page = page;

    // ── Locators — replace with real selectors ──────────────────────────
    // Prefer accessible selectors (getByRole, getByLabel, getByText)
    // Example: this.submitBtn = page.getByRole('button', { name: /submit/i });
    this.pageTitle = page.locator('h1').first();
  }

  /**
   * Navigate to the page
   * @param {string} [path='/']
   */
  async goto(path = '/') {
    await this.page.goto(path, { waitUntil: 'domcontentloaded' });
    await this.page.waitForLoadState('networkidle');
  }

  /**
   * Wait until the page is fully loaded and stable
   */
  async waitForPageReady() {
    await this.page.waitForLoadState('networkidle');
    await expect(this.pageTitle).toBeVisible({ timeout: 10_000 }).catch(() => {});
  }

  // ── Page-specific actions — add your methods below ─────────────────────
}

export { ${cls} };
`;
}

// ─── Spec file template ───────────────────────────────────────────────────────

function specTemplate(name, ast, config) {
  const cls = pascal(name) + 'Page';
  const baseUrl = config?.frontend?.baseUrlGuess || config?.environment?.baseUrl || 'http://localhost:3000';

  // Build test cases from acceptance criteria or defaults
  const tests = ast?.acceptanceCriteria?.length
    ? ast.acceptanceCriteria.map((ac, i) => buildTestCase(ac, i + 1, name))
    : [buildTestCase('happy path — basic functionality', 1, name)];

  // Add standard security + validation tests
  tests.push(buildSecurityTest(name));
  tests.push(buildValidationTest(name));

  return `// @ts-check
/**
 * E2E Test Suite: ${name}
 * Auto-generated by AI QA Framework v2.
 *
 * Story  : ${ast?.title ?? name}
 * Actor  : ${ast?.actor ?? 'المستخدم'}
 * Goal   : ${ast?.goal ?? '—'}
 * BaseURL: ${baseUrl}
 *
 * How to run:
 *   npx playwright test e2e/tests/${name}.spec.js --headed
 *
 * Test data: ../test-data/${name}.testdata.json
 */
import { test, expect } from '@playwright/test';
import { ${cls} } from '../pages/${name}.page.js';
import { attachConsoleAndNetworkErrors, waitForStable } from '../helpers/utils.js';
import { loginAs } from '../helpers/auth.js';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
const __dirname = dirname(fileURLToPath(import.meta.url));

// ── Load test data ─────────────────────────────────────────────────────────
let testData = {};
try {
  testData = JSON.parse(readFileSync(resolve(__dirname, '../../test-data/${name}.testdata.json'), 'utf8'));
} catch {
  console.warn('[${name}.spec] No test data file found — using empty defaults.');
}

// ── Suite setup ────────────────────────────────────────────────────────────
test.describe('${ast?.title ?? name}', () => {

  test.beforeEach(async ({ page }, testInfo) => {
    // Capture all console errors and failed network requests
    await attachConsoleAndNetworkErrors(page, testInfo);
  });

${tests.join('\n\n')}

}); // end describe
`;
}

function buildTestCase(ac, idx, name) {
  const safe = String(ac).replace(/[`$\\]/g, '');
  return `  /**
   * TC-${String(idx).padStart(4, '0')} — ${safe}
   * Type: Functional | Priority: High
   */
  test('TC-${String(idx).padStart(4, '0')}: ${safe}', async ({ page }) => {
    const ui = new ${pascal(name)}Page(page);

    // ARRANGE — navigate to the feature
    await ui.goto(testData.path ?? '/');
    await ui.waitForPageReady();

    // ACT — perform the action being tested
    // TODO: Implement steps for: ${safe}

    // ASSERT — verify the expected outcome
    await expect(page).toHaveURL(/.+/, { timeout: 10_000 });
    // TODO: Add specific assertions for: ${safe}
  });`;
}

function buildSecurityTest(name) {
  return `  /**
   * TC-SEC-001 — Security: Unauthorized access attempt
   * Type: Security | Priority: High | Severity: Critical
   */
  test('TC-SEC-001: Unauthorized access redirects to login', async ({ page }) => {
    // Attempt to access the page without authentication
    await page.goto(testData.path ?? '/');

    // Should redirect to login or show 401/403
    const url = page.url();
    const isRedirectedToAuth = /login|auth|signin/i.test(url)
      || (await page.locator('form[action*="login"], input[type="password"]').count()) > 0;

    // Either redirected to auth page OR still on page (if public)
    // Adjust this assertion based on the actual auth requirement
    console.log(\`Current URL after unauthenticated access: \${url}\`);
    expect(page.url()).toBeTruthy(); // Page must respond
  });`;
}

function buildValidationTest(name) {
  return `  /**
   * TC-VAL-001 — Validation: Empty form submission
   * Type: Validation | Priority: High
   */
  test('TC-VAL-001: Empty required fields show validation errors', async ({ page }) => {
    const ui = new ${pascal(name)}Page(page);
    await ui.goto(testData.path ?? '/');
    await ui.waitForPageReady();

    // Find and click submit without filling fields
    const submitBtn = page.getByRole('button', { name: /submit|save|send|حفظ|إرسال/i });
    if (await submitBtn.count() > 0) {
      await submitBtn.click();
      // Validation messages should appear
      const errorMsg = page.locator('[class*="error"], [class*="invalid"], [role="alert"]');
      if (await errorMsg.count() > 0) {
        await expect(errorMsg.first()).toBeVisible({ timeout: 5_000 });
      }
    } else {
      console.log('[TC-VAL-001] No submit button found — skipping empty form test.');
      test.skip();
    }
  });`;
}

// ─── Shared helper templates ──────────────────────────────────────────────────

function authHelper(config) {
  const baseUrl = config?.frontend?.baseUrlGuess || 'http://localhost:3000';
  const scheme  = config?.auth?.scheme ?? 'unknown';
  return `// @ts-check
/**
 * Auth Helper — reusable authentication utilities
 * Auth scheme detected: ${scheme}
 *
 * Edit test-data/auth.testdata.json to set real credentials.
 */
import { expect } from '@playwright/test';
import { readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
const __dirname = dirname(fileURLToPath(import.meta.url));

/** @type {{ adminUser?: any, agentUser?: any, [key: string]: any }} */
let authData = {};
try {
  const p = join(__dirname, '../../test-data/auth.testdata.json');
  if (existsSync(p)) authData = JSON.parse(readFileSync(p, 'utf8'));
} catch {}

/**
 * Log in as a specific role and navigate to the app.
 * @param {import('@playwright/test').Page} page
 * @param {'admin'|'agent'|'supervisor'|string} role
 */
async function loginAs(page, role = 'admin') {
  const user = authData[role + 'User'] ?? authData.adminUser;
  if (!user) {
    console.warn(\`[auth] No credentials for role "\${role}" in auth.testdata.json\`);
    return;
  }

  await page.goto('${baseUrl}/auth/login', { waitUntil: 'domcontentloaded' });

  // Fill credentials — adjust selectors to match your login form
  const emailField = page.getByLabel(/email|بريد/i).or(page.locator('input[type="email"]')).first();
  const passField  = page.getByLabel(/password|كلمة/i).or(page.locator('input[type="password"]')).first();

  if (await emailField.count() > 0) await emailField.fill(user.email ?? user.username ?? '');
  if (await passField.count()  > 0) await passField.fill(user.password ?? '');

  await page.getByRole('button', { name: /login|sign in|دخول/i }).click();
  await page.waitForLoadState('networkidle');
}

export { loginAs };
`;
}

function utilsHelper() {
  return `// @ts-check
/**
 * Utils — reusable Playwright utilities for the AI QA Framework
 */

/**
 * Attach console error + failed network request collectors to a page.
 * Results are added to the test report automatically.
 *
 * @param {import('@playwright/test').Page} page
 * @param {import('@playwright/test').TestInfo} testInfo
 */
async function attachConsoleAndNetworkErrors(page, testInfo) {
  const consoleErrors = [];
  const networkErrors = [];

  page.on('console', msg => {
    if (msg.type() === 'error') consoleErrors.push(msg.text());
  });

  page.on('response', response => {
    if (response.status() >= 400) {
      networkErrors.push(\`\${response.status()} \${response.url()}\`);
    }
  });

  // Attach on teardown
  testInfo.annotations.push({ type: 'helper', description: 'console+network attached' });
  page._consoleErrors  = consoleErrors;
  page._networkErrors  = networkErrors;
}

/**
 * Wait until the page has no active network requests (stable state).
 * @param {import('@playwright/test').Page} page
 * @param {number} [timeout=10000]
 */
async function waitForStable(page, timeout = 10_000) {
  await page.waitForLoadState('networkidle', { timeout }).catch(() => {});
}

/**
 * Retry an action up to N times.
 * @template T
 * @param {() => Promise<T>} fn
 * @param {number} [retries=3]
 * @returns {Promise<T>}
 */
async function retry(fn, retries = 3) {
  let lastErr;
  for (let i = 0; i < retries; i++) {
    try { return await fn(); } catch (e) { lastErr = e; }
  }
  throw lastErr;
}

/**
 * Simulate realistic human typing with small delays between keystrokes.
 * @param {import('@playwright/test').Locator} locator
 * @param {string} text
 */
async function humanType(locator, text) {
  await locator.click();
  await locator.clear();
  for (const char of text) {
    await locator.type(char, { delay: 30 + Math.random() * 40 });
  }
}

export { attachConsoleAndNetworkErrors, waitForStable, retry, humanType };
`;
}

function instrumentationHelper() {
  return `// @ts-check
/**
 * Instrumentation — captures performance, console, and network metrics.
 * Drop-in replacement for the TypeScript version in testing/helpers/.
 */

/**
 * @param {import('@playwright/test').Page} page
 * @param {import('@playwright/test').TestInfo} testInfo
 */
async function attachConsoleAndNetwork(page, testInfo) {
  const logs = { console: [], network: [] };

  page.on('console', msg => logs.console.push({ type: msg.type(), text: msg.text() }));
  page.on('response', r  => {
    if (r.status() >= 400) logs.network.push({ status: r.status(), url: r.url() });
  });

  testInfo.attach = testInfo.attach ?? (() => {});
}

export { attachConsoleAndNetwork };
`;
}

// ─── Utilities ────────────────────────────────────────────────────────────────

function pascal(s) {
  const raw = s.replace(/(^|[-_])(\w)/g, (_, __, c) => c.toUpperCase());
  // JS identifiers cannot start with a digit — prefix with 'Suite' if needed
  return /^\d/.test(raw) ? `Suite${raw}` : raw;
}


